### ISSUE TITLE
UglifyJS no longer working

### ISSUE THREAD

**Issue by bassrock** [BobKnothe/autoNumeric#112]
Uglify js not wokring anymore. 

It looks like uglify js now breaks on the latest version of the formatter.

```
  '/usr/local/bin/node' '/vagrant/app/Resources/node_modules/.bin/uglifyjs' '-o' '/tmp/outputhiz3NV' '/tmp/inputxRLLor'                                          
  Error Output:                                                                                                                                                  
  Parse error at /tmp/inputxRLLor:879,41                                                                                                                         
  Unexpected token: operator (&&)                                                                                                                                
  Error                                                                                                                                                          
      at new JS_Parse_Error (/vagrant/app/Resources/node_modules/uglify-js/lib/parse.js:189:18)                                                                  
      at js_error (/vagrant/app/Resources/node_modules/uglify-js/lib/parse.js:197:11)                                                                            
      at croak (/vagrant/app/Resources/node_modules/uglify-js/lib/parse.js:657:9)                                                                                
      at token_error (/vagrant/app/Resources/node_modules/uglify-js/lib/parse.js:665:9)                                                                          
      at unexpected (/vagrant/app/Resources/node_modules/uglify-js/lib/parse.js:671:9)                                                                           
      at expr_atom (/vagrant/app/Resources/node_modules/uglify-js/lib/parse.js:1167:9)                                                                           
      at maybe_unary (/vagrant/app/Resources/node_modules/uglify-js/lib/parse.js:1328:19)                                                                        
      at expr_op (/vagrant/app/Resources/node_modules/uglify-js/lib/parse.js:1350:33)                                                                            
      at expr_ops (/vagrant/app/Resources/node_modules/uglify-js/lib/parse.js:1363:16)                                                                           
      at maybe_conditional (/vagrant/app/Resources/node_modules/uglify-js/lib/parse.js:1368:20)                                                                  
      at maybe_assign (/vagrant/app/Resources/node_modules/uglify-js/lib/parse.js:1392:20)                                                                       
      at expression (/vagrant/app/Resources/node_modules/uglify-js/lib/parse.js:1411:20)                                                                         
      at parenthesised (/vagrant/app/Resources/node_modules/uglify-js/lib/parse.js:696:19)   
```

**Comment by BobKnothe** [comment]
Try again.

if not post on jsfiddle.
